### ISSUE TITLE
Replace Mollom SPAM system

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#318]
Mollom, the service that we use to combat SPAM users have announced their end of service. Will be working out 2017, but we should before that replace it.

* https://www.mollom.com/eol

## Protected forms

* Contact: Site-wide contact forms (https://elmcip.net/contact)
* User: User password reset request form

## Scope

* [x] Uninstall and remove mollom
* [x] Replace and Mollom with something else, protecting these same forms Mollom did.

**Comment by steinmb** [comment]
Code that uninstall module and remove permissions. Follow up task is to remove files when 1.28 get released.

**Comment by elmcip** [comment]
See issue #359 -- we should get replacement in asap. Turns out this was a major block for contributors (most of whom forget their passwords in ). Mollom problem blocked them from password reset.

**Comment by elmcip** [comment]
Spam is irritating enough that we should replace as soon as we can. I think users can also get spam through the forms.

**Comment by steinmb** [comment]
Agree. Going to look for a Mollom replacement. This commit completely remove  files:

commit 144a4fd3b9f3eea47b96fd565c7a8f640e08aae1 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Apr 23 21:36:38 2018 +0200

    Issue 318 Remove mollom from file system

        Module no longer installed

**Comment by AlvaroSeica** [comment]
Hi there @steinmb @elmcip !

Since the Mollom filter has been removed, the editor at elmcip dot net account is receiving dozens of spamassassins every day! Here's an example:

<img width="856" alt="menubar_and__feature_request__casino_online_-_inbox_and_paminnelse_-_tilbud_om_barnehageplass_for_sofia_seica-watson_-_inbox" src="https://user-images.githubusercontent.com/6121438/39468838-fd49dda4-4d2c-11e8-890e-970594ac52d9.png">
