### ISSUE TITLE
Review and test hyperlinks in content types help text

### ISSUE THREAD

**Issue by AlvaroSeica** [elmcip/elmcip#343]
@steinmb @elmcip the new data structure (I assume) made by @steinmb now points to different paths: /add to /node/add. I noticed that when creating a teaching resource and cross-ref (and adding) a new platform--the link is broken. I deduce that other links to add new records might be broken as well.

## How to test

Test all links in fields help text. In all content types.

**Comment by hannahackermans** [comment]
I tested all the links in the field help texts. And this is the result. 

Create Person
Every Add link in help texts works. One abnormality:
In the description-section, the “add the anthology” link does not open in a new tab but instead opens the link in the same tab. 

Create Creative Work
Every Add link in help texts works. One abnormality:
In the description-section, the “add the anthology” link does not open in a new tab but instead opens the link in the same tab. 

Create Critical Writing
Most Add links in help texts works. Two abnormalities:
In the Book and Journal Description-section, the “add the critical writing” link does not open in a new tab but instead opens the link in the same tab.
In the References and Attachments-section, the “add the organization” link is broken due to a typo (organiztion) and leads to this page:
<img width="960" alt="screenshot 2017-10-17 15 01 39" src="https://user-images.githubusercontent.com/18713442/31667189-f7345c78-b34e-11e7-9229-4ecc80924a82.png">



Create Platform/Software
Every Add link in help texts works. No abnormalities.

Create Teaching Resource
Most Add links in help texts work. Two abnormalities:
In the References and Attachments-section, the “add the database or archive” link does not open in a new tab but instead opens the link in the same tab.
In the References and Attachments-section, the “add the platform/software” does not work, as Arvaro already pointed out.
![screenshot-2017-10-17 page not found elmcip](https://user-images.githubusercontent.com/18713442/31667205-0588a630-b34f-11e7-96fc-5da34951a90b.png)

Create Publisher
Every Add link in help texts works. One abnormality:
In the Basic Information-section, the “add the event” link does not open in a new tab but instead opens the link in the same tab.

Create Organizations
No Add links to test

Create Event
Every Add link in help texts works. No abnormalities.

Create Databases and Archives
Every Add link in help texts works. No abnormalities.
(had one other field help problem that was not a link, I will add that to #224 ) 

Create Resource Collection 
Every Add link in help texts works. One abnormality:
The “add the creative work” link does not open in a new tab but instead opens the link in the same tab.

If you needs more information here, let me know.

**Comment by AlvaroSeica** [comment]
@steinmb my point is still valid, if it is just the case with that specific link, then it needs to be corrected from https://elmcip.net/add/platform-software to https://elmcip.net/node/add/platform-software

**Comment by steinmb** [comment]
@hannahackermans reviewed all content types, thank you. Changed issue title and reflect this. Also added information about how to test the issue.

**Comment by steinmb** [comment]
commit 15dbf8cf0607e1f84cbff6edac8a3b4dc9f1c251 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Nov 13 17:07:35 2017 +0100

    Issue 343 Improve research collection fields help text links

    The “add the creative work” link does not open in a
    new tab but instead opens the link in the same tab.

commit 9b3f20ae2010909d88913d399d08ba841832a363
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Nov 13 16:59:04 2017 +0100

    Issue 343 Improve Publisher fields help text links

    In the Basic Information-section, the “add the event”
    link does not open in a new tab but instead opens the
    link in the same window.

commit 79f53aadd3268f51bca40260538346839c714783
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Nov 13 16:48:41 2017 +0100

    Issue 343 Improve critical writing links in help texts.

    In the Book and Journal Description-section, the
    “add the critical writing” link does not open in a new tab.

    In the References and Attachments-section, the
    “add the organization” link is broken due to a typo.

commit b8106fd7f2515a2b4cd45c369c0f0f7e59448724
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Nov 13 16:34:26 2017 +0100

    Issue 343 Creative Work make "add the anthology" open in tab

    In the description-section, the “add the anthology” link
    did not open in a new tab, but instead opens the page.

commit 0ac1820363f01aa9184dfee30e2646485de8c392
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Nov 13 16:10:42 2017 +0100

    Issue 343 Fix typo in research_collection help text link.
