### ISSUE TITLE
Media Browser not displaying previous uploaded images?

### ISSUE THREAD

**Issue by AlvaroSeica** [elmcip/elmcip#351]
Check elmcip.net/node/7009

![edit_creative_work_the_pen___elmcip](https://user-images.githubusercontent.com/6121438/30810986-1d4dd276-a207-11e7-9b78-959a265ce7b0.png)

**Comment by steinmb** [comment]
Works OK in production. Notice that you point to both production and test.elmcip.net. Test do not have all the media due to excessive storage space and it will show up like in your screenshot.

We had a proxy setup that in test.elmcip.net one the fly downloaded the needed files from production. In issue #266 did we need to disable it due to enormous pdf file that made us run out of memory and time. As a test have I re-enabled the proxy again. Would be nice to have files to correctly show up there also.

* https://elmcip.net/creative-work/pen-0
* https://test.elmcip.net/creative-work/pen-0
