### ISSUE TITLE
Bug in Front Page Date Assignment of Creative Works?

### ISSUE THREAD

**Issue by AlvaroSeica** [elmcip/elmcip#358]
Check the date indexation, is there a bug?

<img width="636" alt="elmcip___electronic_literature_as_a_model_of_creativity_and_innovation_in_practice" src="https://user-images.githubusercontent.com/6121438/38434164-42ff5e3c-3982-11e8-9025-31a3f254658d.png">

**Comment by steinmb** [comment]
Checked now and front block contain newer posts. Stale content here might be caused by that we are in the process of shutting down Norstore and maintenance tasks might not run as they should anymore. Issue #341 is what I am currently working on. I think we migrate in a few days. At least I hope we do.
