### ISSUE TITLE
Allow contributors to set and change record status

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#369]
Until we have librarian and a strict editorial flow we should allow also contributor to set and change the record status.

## Fields

* Content type: All KB types that have it.
* Field: field_record_status_tax 

Alter permissions settings.

## How to test

* Create new record as a contributor only user
* Alter a existing record status

**Comment by steinmb** [comment]
Just tested in production. Contributors are allowed to change the status of a existing record, but not allowed to set the initial value when creating a new one.

**Comment by steinmb** [comment]
commit 7e47a3e50e3b50b3d341eb5c98ee74e02e27c0a4 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Apr 27 15:46:51 2018 +0200

    Issue 369 Allow contributor to create record status

    They where only allowed to change status on existing
    records.

**Comment by hannahackermans** [comment]
@elmcip Here's the issue that decided contributors can change the record status. 

We discussed this on Friday: 
On critical writing, contributors can change the status but not add notes, whereas on creative writing, they can both change the status and add a note. @elmcip said on Friday that we should remove record status for the contributors altogether. 

If we want to keep this functionality it should include the notes field because if you change a field to "revisions required" for example, it is also useful to add why and how. If this is the way we god, I can check in test for all the different content types which fields are in the record status. 

@steinmb and @elmcip, please discuss here :)
