### ISSUE TITLE
Add series field to creative work

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#435]
The series field (which appears on critical writing and is a critical writing content type) should also be a field on the creative work core information entry tab. The help text should be the same as on critical writing.

For example, the books in the Using Electricity series (Such as The Truest: https://elmcip.net/creative-work/truelist) are creative works, but part of a book series.

**Comment by steinmb** [comment]
commit bca752274eb85fc3853f7055f7135f12d8cb5c19 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Jan 30 17:25:24 2020 +0100

    Issue 435 Create work new field: field_series_ref

**Comment by hannahackermans** [comment]
I was just answering a question to someone who wanted to add various creative works in a series of creative works, and I have some follow-up questions in on the 'series' field in creative works (description tab)

1) Right now, I think the 'series' field autocompletes critical writing, even in the creative work form, meaning that we can only say that a creative work is part of a series of critical writing. Is that how it is meant to work? Because it seems more logical if the creative work would be part of a series of creative works.

2) To be honest I am not sure what the 'series' field is supposed to add to the two fields below it, namely 'Appears in' (which links to critical writing records) and 'Part of another work' (which links to creative works).

Could you, @elmcip and @steinmb , clarify this for me?

**Comment by elmcip** [comment]
We resolved Hannah's question buy the series does not show up as a hyperlink, just as plain text. It should display as a link.

**Comment by hannahackermans** [comment]
<img width="245" alt="Screenshot 2020-09-18 15 19 20" src="https://user-images.githubusercontent.com/18713442/93602370-d1612e00-f9c2-11ea-81da-084ef0097ad5.png">

**Comment by steinmb** [comment]
Please don't move more issues into this release.

**Comment by steinmb** [comment]
Haha, I need a weekend. Forget my comment above 🤦

**Comment by steinmb** [comment]
commit f8d1b223862323c5b04ef783ded051cb792c17f7 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Sep 21 13:26:43 2020 +0200

    Issue 435 Creative work book series ref. did not link to entity
