### ISSUE TITLE
Approved by librarian state should be placed in "editorial status" editing a record

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#445]
On all content types that have library approved status field, move the entry field to the same tab as Record Status and eliminate "Flags" tab.

**Comment by Antikrista** [comment]
Changes on librarian's acc interface have to look like this:

<img width="1085" alt="Screenshot 2020-02-05 at 15 17 58" src="https://user-images.githubusercontent.com/58079572/73849926-161cc800-482b-11ea-929e-acff2985d632.png">

Moving the Library Approved field into the Status field will simplify the work of librarians since now we have a lot of librarians approved records but with still the same status. When status and proving will be on the same tab, that much much more possible that both fields will be marked by librarians.

@elmcip Scott, if you see that proving's field needs to call different, give me a hint.

**Comment by audgjersdal** [comment]
testing if I can write here

**Comment by elmcip** [comment]
You can write here, yes.

On Sep 11, 2020, at 4:47 PM, audgjersdal <notifications@github.com<mailto:notifications@github.com>> wrote:



testing if I can write here

**Comment by audgjersdal** [comment]
This is what we wrote in the report: "In the pilot we concentrated on books (monographs), critical writing, not yet reviewed. But, we didn't find a way to make a subset of records satisfying this requirements. It is too time-consuming to find the records by clicking through the alternatives to find the right ones, so this has to be enhanced." I will write a little together with else.skjondal@uib.no next week.
