### ISSUE TITLE
Warnings on KB's pages

### ISSUE THREAD

**Issue by Antikrista** [elmcip/elmcip#448]
Opening a Critical Writing 'Nettitudes' I got the warning:
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/58079572/73931446-9cdbae80-48d8-11ea-99e1-45160da2c170.png">

https://test.elmcip.net/critical-writing/nettitudes

Regardless of it, I have done only one action - stanged status from 'not yet reviewed' to 'revision required'

**Comment by Antikrista** [comment]
Warnings appear on an editing mode.

Next warning:
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/58079572/73935415-c26cb600-48e0-11ea-83b5-96d0348988ae.png">
https://test.elmcip.net/node/14769/edit

**Comment by steinmb** [comment]
Thank you for noticing :) 
It is a known warning that we have had for the last year. Only visible on test or in development. Nothing critical. PHP 7.2.x thingy. Warning is fixed in the upcoming version of the date module that is complaint https://www.drupal.org/project/date/issues/2867810, though we still have one issue that left that blocks the release - https://www.drupal.org/project/date/issues/3016390

I think we can close this since it is nothing wrong with our application or its data. I have verified this previously in development while working on the next release of the module. https://www.drupal.org/project/issues/search/date?text=&assigned=&submitted=&project_issue_followers=steinmb&issue_tags_op=%3D&issue_tags= it's my Drupal ID

**Comment by Antikrista** [comment]
Thank you for reacting! ok, you know and solve the issue on your side. So I close it for now
