### ISSUE TITLE
Priority issue from the library

### ISSUE THREAD

**Issue by audgjersdal** [elmcip/elmcip#456]
We need to choose: 
Critical writing
Publication type: Monographs (books)
Record status: Not yet reviewed
Library approved: yes or no

Then we have the right subset we at the library can choose records from. Otherwise we can not contribute
https://elmcip.net/knowledgebase

![Screenshot 2020-09-21 at 13 06 16](https://user-images.githubusercontent.com/683617/93759852-445ce580-fc0b-11ea-9579-62c239f36063.png)
![Screenshot 2020-09-21 at 13 06 06](https://user-images.githubusercontent.com/683617/93759853-458e1280-fc0b-11ea-9ed0-4fd0c4a0bbb7.png)

## How to test

TBD

## Original report
Hello, we have made a description of the most important problem. We at the library has time to work on ELMCIP now while we are on home office, and it would be great if this could be done asap. I hope it is possible to access the word document with the description. We can not do our work with Elmcip before this functionality is in place.
 

[Approved by librarian state should be placed in.docx](https://github.com/elmcip/elmcip/files/5219929/Approved.by.librarian.state.should.be.placed.in.docx)

**Comment by steinmb** [comment]
Lets take the content out the word file. Please not add word files to issues, they are not searchable, user friendly or developer friendly.

**Comment by audgjersdal** [comment]
What information do you need?

**Comment by steinmb** [comment]
It seems out of sync of the changes we already have done. Trying to understand this issue and to me it seems we already have have it all. Please have a look at issue #461 and the issue it was split out from to that implemented the changes you currently see on test.

**Comment by audgjersdal** [comment]
Ok just tell us how we can find the records or example:
Critical writing
Publication type: Monographs (books)
Record status: Not yet reviewed
Library approved:  no

**Comment by steinmb** [comment]
New functionality is not found in our production system but in our development test server. It needs to be tested and reviewed and approved by the end users before we roll it into production. The test-server is a safe place to test stuff out without the fear of polluting production content/status. Once a day the test server is re-installed and anything you created is removed. A safe sandbox to test stuff out.

Look at issue #461 - It contain link to the librarian status page at our **test** system.

**Comment by audgjersdal** [comment]
Yesterday I could access test.elmcip.net but today I need username and password, and I don't have this

**Comment by elmcip** [comment]
Use: test, Pass: test

**Comment by hannahackermans** [comment]
If I understand correctly, the thing that is missing for Aud is a filter for library status on all critical writings (https://elmcip.net/critical_writing). 

As this filter will be used to find records that have not yet been reviewed by librarians, it is important that "- None -" is also one of the options, because that indicates it has not been touched by a librarian yet. 

So the options for that filter should be:
`<Any>` (when the filter is not used)
`- None -` (not reviewed by librarian yet)
`Not approved by librarian`
`Approved by librarian`

@audgjersdal can you please confirm this?

**Comment by hannahackermans** [comment]
Reply from Aud:
> Hi, thanks for this. Else is on vacation today and Monday. I am on vacation next week until Thursday. We will look at it as soon as possible next week!
> Best, Aud
>

**Comment by audgjersdal** [comment]
Else and me has looked at Hannahs comment. We don't need the _None_ (not reviewed by librarian yet) alternative.

What we need is:
<Any> (when the filter is not used) [That is: All. The set of records including those which are not approved by librarian plus those which are approved by librarian]

Not approved by librarian
Approved by librarian

**Comment by elmcip** [comment]
“None” is there to indicate the record has not yet been looked at by a librarian. Which is a different state than the other two.

**Comment by audgjersdal** [comment]
well yes, but we don't think we need to find those records "None".

**Comment by elmcip** [comment]
Doesn’t it make sense to know which ones have not yet been examined?

On Oct 15, 2020, at 2:57 PM, audgjersdal <notifications@github.com<mailto:notifications@github.com>> wrote:



well yes, but we don't think we need to find those records "None".

**Comment by audgjersdal** [comment]
Well, we can't see that we need alternative "none". we need to find records that's not approved, so we know which to enhance, and thereafter approve. Then we also need to find the approved records, sort by time it was approved, so we can proofread the most recent records.

**Comment by hannahackermans** [comment]
![Screenshot 2020-10-08 16 59 05](https://user-images.githubusercontent.com/18713442/96256229-8aae2600-0fb8-11eb-9704-043bb956d3e4.png)

We see the alternative "- None -" as essential, because it allows us to know what has been looked at by the library and what remains to be done. This is different than “Not approved by librarian”, which would indicate a resource that the library has looked at, but has not approved.

@audgjersdal The screenshot above shows the new librarian status. It defaults to "- None -" and then you have the option to set it to "Not approved by librarian" and "Approved by librarian".

If you use a filter and set it to "Not approved by librarian", it will only show you the records that you have already looked at and labeled with "Not approved by librarian". All the records you have not done anything with yet, are labeled "- None -" and will not be shown in this filter. 

So to see all the records you have done nothing with yet, you will need the "- None -" option.

**Comment by audgjersdal** [comment]
for the library, it has no relevance if we have looked at a record or not

**Comment by audgjersdal** [comment]
i think hannah, else and me should meet about this! next week?

**Comment by hannahackermans** [comment]
Update after the meeting:
![Screenshot_2020-10-23 Library approved records ELMCIP](https://user-images.githubusercontent.com/18713442/97011984-a4ff7b00-1547-11eb-8138-abff85a277c4.png)

On the Library approved records page, we have almost everything that the library needs, including: 
1 Record type (Critical writing)
2 Publication type (Monographs (books))
3 Librarian status (approved or not approved)
4 Got a librarian status (yes or no)
You can find the page here: https://elmcip.net/knowledgebase/library_status?type_1=All&field_pubtype_tax_tid=All&flagged=0&field_record_status_lib_value=All&field_record_status_lib_value_1=All

Aud also asked for a field for the regular record status filter. So far, the library has worked on records that were "not yet reviewed", but there are no more monographs that are not "not yet reviewed" (see empty list here: https://elmcip.net/critical_writing?field_language_tax_tid=All&field_pubtype_tax_tid=1590&field_record_status_tax_tid=1489&title=)

@audgjersdal does that mean you will move on to the records status "record approved"? Or does the record status not matter anymore? Please let us know if you still need a record status filter on the Library approved records page,

**Comment by audgjersdal** [comment]
Thanks. Else will look at it. (she is on vacation today).

**Comment by audgjersdal** [comment]
Feedback from user side:
Thanks for this.
For us it is confusing to start with "Library approved" when the result after working with the filters is "library approved",  if we choose this. But we can also choose to make a list over records that are not library approved, and then this title is misleading.

 "Librarian status". This is the functionality we need, so thanks for this. But we don't need all the other filters. What we need is the "librarian status" filter on this page:
https://elmcip.net/critical_writing?field_language_tax_tid=All&field_pubtype_tax_tid=1590&field_record_status_tax_tid=1489&title=

"Aud also asked for a field for the regular record status filter." I don't think so. 
I (and Else) have asked for a "librarian status" filter here, on this page:
https://elmcip.net/critical_writing?field_language_tax_tid=All&field_pubtype_tax_tid=1590&field_record_status_tax_tid=1489&title=

**Comment by hannahackermans** [comment]
Hi @audgjersdal Since this is something only Else and you will be working with, we will use the page I indicated as the place for new filters that are useful for you, not on the critical writing page. 

` For us it is confusing to start with "Library approved" when the result after working with the filters is "library approved", if we choose this. But we can also choose to make a list over records that are not library approved, and then this title is misleading.`
I see your point, but that is probably easily solved by renaming the page to "Librarian filters" or something like that. If you don't want the regular record status filter, everything you need is on this page: https://elmcip.net/knowledgebase/library_status?type_1=All&field_pubtype_tax_tid=All&flagged=0&field_record_status_lib_value=All&field_record_status_lib_value_1=All

**Comment by audgjersdal** [comment]
we choose "Librarian status-not approved by librarian" and we don't get a list: "No records found".

**Comment by hannahackermans** [comment]
> 
> 
> we choose "Librarian status-not approved by librarian" and we don't get a list: "No records found".

That is because there are no records labeled with "not approved by librarian". In the old system, everything was 'not approved' until you used the toggle to approve it. But in the new system, the default is '- None -' and "not approved by librarian" is an active choice. Since there are no records labeled with "not approved by librarian" yet, it returns a "No records found". 

After you start using the "not approved by librarian" label in the records, the filter "Librarian status-not approved by librarian" will return those records in a list. 

If you are looking for records that you have not yet worked with, use the "Got a librarian status" filter and choose "no". This will show a list of all records that have not yet been approved.

**Comment by steinmb** [comment]
Personally do not see anything left here. Closing. Please create new issues for any features missing or not working.
