### ISSUE TITLE
Critical writing data export view - Creative Works referenced ID formatter is label not entity id

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#463]
This is a major issue for me that should have a quick fix. I need this export to complete a paper I'm writing now. This data export view: https://elmcip.net/critical-writing-referencing-creative-works-data

Shows the title of the creative work reference in the Creative Works referenced ID field. There should be a node ID in that field rather than the title label. 

Can we hot fix this and get it on test? I need this export for the article I'm currently writing.

<img width="1209" alt="Screen Shot 2020-10-12 at 3 50 08 PM" src="https://user-images.githubusercontent.com/5831053/95754713-bb821880-0ca3-11eb-86ee-5ac92a994c55.png">

## How to test

* Go to: https://test.elmcip.net/critical-writing-referencing-creative-works 
* There is two data exports on this page. Test them both.

**Comment by steinmb** [comment]
Quick fix though NIRD in Norway is down everywhere due to updates - https://opslog.sigma2.no/2020/10/13/downtime-continues-for-nird/

commit e46df6024591d35a4c0f80b701193bc6d2969e17 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Tue Oct 13 13:35:49 2020 +0200

    Issue 463 Entity ID ref. was actually lable

    Quick update to the Creative work data export

diff --git a/modules/elmcip_data_export/elmcip_data_export.views_default.inc b/modules/elmcip_data_export/elmcip_data_export.views_default.inc
index cfbe98a..bcc2fe6 100644
--- a/modules/elmcip_data_export/elmcip_data_export.views_default.inc
+++ b/modules/elmcip_data_export/elmcip_data_export.views_default.inc
@@ -7691,7 +7691,7 @@ function elmcip_data_export_views_default_views() {
   $handler->display->display_options['fields']['field_node_ref_work_1']['table'] = 'field_data_field_node_ref_work';
   $handler->display->display_options['fields']['field_node_ref_work_1']['field'] = 'field_node_ref_work';
   $handler->display->display_options['fields']['field_node_ref_work_1']['label'] = 'Creative Works referenced ID';
-  $handler->display->display_options['fields']['field_node_ref_work_1']['type'] = 'node_reference_nid';
+  $handler->display->display_options['fields']['field_node_ref_work_1']['type'] = 'entityreference_entity_id';
   $handler->display->display_options['fields']['field_node_ref_work_1']['group_rows'] = FALSE;
   $handler->display->display_options['fields']['field_node_ref_work_1']['delta_offset'] = '0';
   /* Field: Content: Author */
